
import { Event } from './types';

export const INITIAL_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Nexus 2024 - Tech Symposium',
    date: '2024-10-26',
    description: 'A national level tech symposium with coding contests, paper presentations, and workshops on AI/ML.',
    schedule: '10:00 AM - Inauguration\n11:00 AM - Keynote Speech\n12:00 PM - Coding Contest (Prelims)\n02:00 PM - Workshop on React\n04:00 PM - Valedictory',
    venue: 'Main Auditorium, Tech University',
    rules: '1. All participants must carry their college ID.\n2. Laptops are mandatory for coding contests.\n3. No plagiarism in paper presentations.',
    contact: 'Dr. Alan Smith - 9876543210',
    organizerId: 'org-1',
    clubName: 'Tech Innovators Club',
    maxRegistrations: 150,
    registrationStatus: 'OPEN',
  },
  {
    id: '2',
    title: 'Vibrations - Annual Cultural Fest',
    date: '2024-11-15',
    description: 'Experience a vibrant celebration of art, music, and dance. Featuring celebrity performances and inter-college competitions.',
    schedule: '09:00 AM - Dance Competition (Solo)\n11:00 AM - Music Battle (Band)\n01:00 PM - Fashion Show\n03:00 PM - Street Play\n06:00 PM - Celebrity Night',
    venue: 'University Grounds',
    rules: '1. Registration is mandatory for all competitions.\n2. Rules for each event will be shared separately.\n3. Judges\' decisions are final.',
    contact: 'Prof. Jane Doe - 8765432109',
    organizerId: 'org-2',
    clubName: 'Cultural Committee',
    maxRegistrations: 500,
    registrationStatus: 'OPEN',
  },
  {
    id: '3',
    title: 'InnovateX - Entrepreneurship Summit',
    date: '2024-12-05',
    description: 'A summit for budding entrepreneurs to connect with investors, attend workshops, and pitch their startup ideas.',
    schedule: '09:30 AM - Registration\n10:00 AM - Panel Discussion: The Future of Startups\n11:30 AM - Workshop: From Idea to MVP\n02:00 PM - Startup Pitch Competition\n05:00 PM - Networking High Tea',
    venue: 'Convention Center, Business School',
    rules: '1. Pitch decks must be submitted by Dec 1st.\n2. Each team can have a maximum of 4 members.\n3. Open to students and recent graduates.',
    contact: 'E-Cell Coordinator - 7654321098',
    organizerId: 'org-3',
    clubName: 'Entrepreneurship Cell',
    maxRegistrations: 100,
    registrationStatus: 'PAUSED',
  },
    {
    id: '4',
    title: 'Code Sprint - 24 Hour Hackathon',
    date: '2024-11-02',
    description: 'Join the ultimate coding marathon. Build, innovate, and compete for amazing prizes.',
    schedule: 'Day 1, 10:00 AM - Kickoff\nDay 1, 11:00 AM - Hacking begins\nDay 2, 11:00 AM - Submissions close\nDay 2, 01:00 PM - Judging & Demos',
    venue: 'Computer Labs, Block A',
    rules: '1. Teams of 2-4 members.\n2. All code must be written during the event.\n3. Pre-built libraries are allowed.',
    contact: 'Hackathon Team - code@ease.edu',
    organizerId: 'org-1',
    clubName: 'Tech Innovators Club',
    maxRegistrations: 50,
    registrationStatus: 'CLOSED',
  },
];